#!/bin/sh
# This file should be located in .husky/commit-msg

file_path="$1"
content=$(cat "$file_path")
first_word=$(echo "$content" | awk '{print $1}' | sed 's/:$//')

case "$first_word" in
  feat)      prefix=":sparkles:" ;;
  fix)       prefix=":bug:" ;;
  docs)      prefix=":memo:" ;;
  style)     prefix=":lipstick:" ;;
  refactor)  prefix=":recycle:" ;;
  perf)      prefix=":zap:" ;;
  test)      prefix=":white_check_mark:" ;;
  chore)     prefix=":truck:" ;;
  revert)    prefix=":rewind:" ;;
  wip)       prefix=":construction:" ;;
  build)     prefix=":construction_worker:" ;;
  ci)        prefix=":green_heart:" ;;
  upgrade)   prefix=":arrow_up:" ;;
  downgrade) prefix=":arrow_down:" ;;
  *)
    echo "Commit type '$first_word' not recognized. Valid types: feat, fix, docs, style, refactor, perf, test, chore, revert, wip, build, ci, upgrade, downgrade"
    exit 1
    ;;
esac

echo "${prefix} ${content}" > "$file_path"

npx commitlint --edit "$1"